In [15]:
import json
import glob
from tqdm import tqdm
from pathlib import Path

In [16]:
training_path = '../dataset/train/'
testing_path = '../dataset/test/'


In [17]:
training_graphs = glob.glob(training_path +'*.json')
print(training_graphs)

['../dataset/train\\0.json', '../dataset/train\\1.json', '../dataset/train\\10.json', '../dataset/train\\11.json', '../dataset/train\\12.json', '../dataset/train\\13.json', '../dataset/train\\14.json', '../dataset/train\\15.json', '../dataset/train\\16.json', '../dataset/train\\17.json', '../dataset/train\\18.json', '../dataset/train\\19.json', '../dataset/train\\2.json', '../dataset/train\\20.json', '../dataset/train\\21.json', '../dataset/train\\22.json', '../dataset/train\\23.json', '../dataset/train\\24.json', '../dataset/train\\25.json', '../dataset/train\\26.json', '../dataset/train\\27.json', '../dataset/train\\28.json', '../dataset/train\\29.json', '../dataset/train\\3.json', '../dataset/train\\30.json', '../dataset/train\\31.json', '../dataset/train\\32.json', '../dataset/train\\33.json', '../dataset/train\\34.json', '../dataset/train\\35.json', '../dataset/train\\36.json', '../dataset/train\\37.json', '../dataset/train\\38.json', '../dataset/train\\39.json', '../dataset/train

In [18]:
training_graphs = glob.glob(training_path + "*.json")
testing_graphs = glob.glob(testing_path + "*.json")
graph_pairs = training_graphs + testing_graphs
global_labels = set()
# 预处理所有的graph
for graph_pair in tqdm(graph_pairs):
    data = json.load(open(graph_pair))
    #print(data)
    global_labels = global_labels.union(set(data["labels_1"]))
    global_labels = global_labels.union(set(data["labels_2"]))
global_labels = list(global_labels)
global_labels = {val:index  for index, val in enumerate(global_labels)}
number_of_labels = len(global_labels)

print()
print(number_of_labels)

100%|██████████| 100/100 [00:00<00:00, 2040.66it/s]
16



In [19]:
from tqdm import trange
import time
for i in trange(100, leave=True, desc="Epoch"):
    time.sleep(0.2)


Epoch: 100%|██████████| 100/100 [00:20<00:00,  4.88it/s]


In [20]:
import json
data = json.load(open('../dataset/train/0.json'))
print(data)

{'labels_1': ['11', '11', '9', '11', '10', '7', '13', '11', '10', '9', '11', '8', '8', '10', '13'], 'labels_2': ['8', '11', '5', '11', '9', '7', '9', '7', '12', '11', '11', '11', '10', '10', '14'], 'graph_2': [[0, 1], [0, 4], [0, 5], [0, 8], [0, 11], [0, 12], [0, 13], [0, 14], [1, 2], [1, 3], [1, 6], [1, 7], [1, 8], [1, 10], [1, 11], [1, 12], [1, 13], [1, 14], [2, 9], [2, 12], [2, 5], [2, 14], [3, 4], [3, 6], [3, 7], [3, 8], [3, 9], [3, 10], [3, 11], [3, 12], [3, 13], [3, 14], [4, 6], [4, 8], [4, 9], [4, 10], [4, 11], [4, 13], [4, 14], [5, 7], [5, 9], [5, 10], [5, 13], [5, 14], [6, 8], [6, 9], [6, 10], [6, 11], [6, 12], [6, 14], [7, 8], [7, 9], [7, 10], [7, 14], [8, 9], [8, 10], [8, 11], [8, 12], [8, 13], [8, 14], [9, 10], [9, 11], [9, 13], [9, 14], [10, 11], [10, 12], [10, 14], [11, 12], [11, 13], [11, 14], [12, 13], [12, 14], [13, 14]], 'ged': 11, 'graph_1': [[0, 1], [0, 2], [0, 3], [0, 4], [0, 6], [0, 7], [0, 8], [0, 10], [0, 12], [0, 13], [0, 14], [1, 3], [1, 4], [1, 6], [1, 7], [1

In [21]:
#data['graph_1']
#for x, y in data["graph_1"]:
#    print(x, y)
# 边记为 e ， 则edges_1的尺寸为 2e * 2
edges_1 = data["graph_1"] + [[y, x] for x, y in data["graph_1"]]
print(edges_1)

[[0, 1], [0, 2], [0, 3], [0, 4], [0, 6], [0, 7], [0, 8], [0, 10], [0, 12], [0, 13], [0, 14], [1, 3], [1, 4], [1, 6], [1, 7], [1, 8], [1, 9], [1, 10], [1, 11], [1, 13], [1, 14], [2, 5], [2, 6], [2, 7], [2, 9], [2, 10], [2, 11], [2, 12], [2, 14], [3, 4], [3, 5], [3, 6], [3, 7], [3, 8], [3, 9], [3, 11], [3, 13], [3, 14], [4, 5], [4, 6], [4, 8], [4, 9], [4, 10], [4, 13], [4, 14], [5, 6], [5, 7], [5, 12], [5, 13], [6, 7], [6, 8], [6, 10], [6, 11], [6, 12], [6, 13], [6, 14], [7, 8], [7, 9], [7, 10], [7, 12], [7, 14], [8, 9], [8, 10], [8, 12], [8, 14], [9, 10], [9, 11], [9, 14], [10, 11], [10, 13], [10, 14], [11, 13], [11, 14], [12, 13], [12, 14], [13, 14], [1, 0], [2, 0], [3, 0], [4, 0], [6, 0], [7, 0], [8, 0], [10, 0], [12, 0], [13, 0], [14, 0], [3, 1], [4, 1], [6, 1], [7, 1], [8, 1], [9, 1], [10, 1], [11, 1], [13, 1], [14, 1], [5, 2], [6, 2], [7, 2], [9, 2], [10, 2], [11, 2], [12, 2], [14, 2], [4, 3], [5, 3], [6, 3], [7, 3], [8, 3], [9, 3], [11, 3], [13, 3], [14, 3], [5, 4], [6, 4], [8, 4]

In [22]:
import numpy as np

edges_1_T = np.array(edges_1, dtype=np.int64).T
# edges_1_T的尺寸为 2* 2e; 上面的行是出发顶点；下面的行是目标顶点
print(edges_1_T)

[[ 0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  1  2  2  2
   2  2  2  2  2  3  3  3  3  3  3  3  3  3  4  4  4  4  4  4  4  5  5  5
   5  6  6  6  6  6  6  6  7  7  7  7  7  8  8  8  8  9  9  9 10 10 10 11
  11 12 12 13  1  2  3  4  6  7  8 10 12 13 14  3  4  6  7  8  9 10 11 13
  14  5  6  7  9 10 11 12 14  4  5  6  7  8  9 11 13 14  5  6  8  9 10 13
  14  6  7 12 13  7  8 10 11 12 13 14  8  9 10 12 14  9 10 12 14 10 11 14
  11 13 14 13 14 13 14 14]
 [ 1  2  3  4  6  7  8 10 12 13 14  3  4  6  7  8  9 10 11 13 14  5  6  7
   9 10 11 12 14  4  5  6  7  8  9 11 13 14  5  6  8  9 10 13 14  6  7 12
  13  7  8 10 11 12 13 14  8  9 10 12 14  9 10 12 14 10 11 14 11 13 14 13
  14 13 14 14  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1
   1  2  2  2  2  2  2  2  2  3  3  3  3  3  3  3  3  3  4  4  4  4  4  4
   4  5  5  5  5  6  6  6  6  6  6  6  7  7  7  7  7  8  8  8  8  9  9  9
  10 10 10 11 11 12 12 13]]


In [23]:
print(data["labels_1"])
print(len(data["labels_1"]))

['11', '11', '9', '11', '10', '7', '13', '11', '10', '9', '11', '8', '8', '10', '13']
15


In [24]:
import torch

torch.from_numpy(edges_1_T).type(torch.long)

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,
          3,  3,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  6,  6,  6,  6,  6,
          6,  6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11,
         11, 12, 12, 13,  1,  2,  3,  4,  6,  7,  8, 10, 12, 13, 14,  3,  4,  6,
          7,  8,  9, 10, 11, 13, 14,  5,  6,  7,  9, 10, 11, 12, 14,  4,  5,  6,
          7,  8,  9, 11, 13, 14,  5,  6,  8,  9, 10, 13, 14,  6,  7, 12, 13,  7,
          8, 10, 11, 12, 13, 14,  8,  9, 10, 12, 14,  9, 10, 12, 14, 10, 11, 14,
         11, 13, 14, 13, 14, 13, 14, 14],
        [ 1,  2,  3,  4,  6,  7,  8, 10, 12, 13, 14,  3,  4,  6,  7,  8,  9, 10,
         11, 13, 14,  5,  6,  7,  9, 10, 11, 12, 14,  4,  5,  6,  7,  8,  9, 11,
         13, 14,  5,  6,  8,  9, 10, 13, 14,  6,  7, 12, 13,  7,  8, 10, 11, 12,
         13, 14,  8,  9, 10, 12, 14,  9, 10, 12, 14, 10, 11, 14, 11

In [36]:
print(data['ged'])
norm_ged = data["ged"]/(0.5*(len(data["labels_1"])+len(data["labels_2"])))
print(norm_ged)
print(np.exp(-norm_ged).reshape(1, 1))
print(torch.from_numpy(np.exp(-norm_ged).reshape(1, 1)))
print(torch.from_numpy(np.exp(-norm_ged).reshape(1, 1)).view(-1))
#torch.from_numpy(np.exp(-norm_ged).reshape(1, 1)).view(-1).float()

11
0.7333333333333333
[[0.4803053]]
tensor([[0.4803]], dtype=torch.float64)
tensor([0.4803], dtype=torch.float64)


### labels_1 和 labels_2 应该是图节点的取值

In [39]:
data['labels_1']

['11',
 '11',
 '9',
 '11',
 '10',
 '7',
 '13',
 '11',
 '10',
 '9',
 '11',
 '8',
 '8',
 '10',
 '13']

In [40]:
data['labels_2']

['8',
 '11',
 '5',
 '11',
 '9',
 '7',
 '9',
 '7',
 '12',
 '11',
 '11',
 '11',
 '10',
 '10',
 '14']

In [8]:
import torch 
x=torch.arange(15).view(5,3)
x=x.float()

In [9]:
torch.mean(x,dim=0)

tensor([6., 7., 8.])